# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parsergui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 330)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(590, 330))
        MainWindow.setMaximumSize(QtCore.QSize(590, 330))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.magBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.magBrowseButton.setGeometry(QtCore.QRect(510, 50, 71, 21))
        self.magBrowseButton.setObjectName("magBrowseButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_2.setObjectName("label_2")
        self.subBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.subBrowseButton.setGeometry(QtCore.QRect(380, 10, 71, 21))
        self.subBrowseButton.setObjectName("subBrowseButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 101, 20))
        self.label_3.setObjectName("label_3")
        self.topBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.topBrowseButton.setGeometry(QtCore.QRect(510, 110, 71, 21))
        self.topBrowseButton.setObjectName("topBrowseButton")
        self.runParseButton = QtWidgets.QPushButton(self.centralwidget)
        self.runParseButton.setGeometry(QtCore.QRect(510, 270, 75, 23))
        self.runParseButton.setObjectName("runParseButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 260, 491, 41))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 71, 16))
        self.label_4.setObjectName("label_4")
        self.saveAsMAT = QtWidgets.QCheckBox(self.centralwidget)
        self.saveAsMAT.setGeometry(QtCore.QRect(90, 150, 81, 17))
        self.saveAsMAT.setChecked(True)
        self.saveAsMAT.setObjectName("saveAsMAT")
        self.saveAsCSV = QtWidgets.QCheckBox(self.centralwidget)
        self.saveAsCSV.setGeometry(QtCore.QRect(90, 170, 81, 17))
        self.saveAsCSV.setObjectName("saveAsCSV")
        self.saveAsXLSX = QtWidgets.QCheckBox(self.centralwidget)
        self.saveAsXLSX.setGeometry(QtCore.QRect(90, 190, 81, 17))
        self.saveAsXLSX.setObjectName("saveAsXLSX")
        self.outputBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.outputBrowseButton.setGeometry(QtCore.QRect(510, 220, 71, 21))
        self.outputBrowseButton.setObjectName("outputBrowseButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 101, 16))
        self.label_5.setObjectName("label_5")
        self.magCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.magCheckBox.setGeometry(QtCore.QRect(70, 50, 111, 21))
        self.magCheckBox.setChecked(False)
        self.magCheckBox.setObjectName("magCheckBox")
        self.topCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.topCheckBox.setGeometry(QtCore.QRect(70, 110, 121, 21))
        self.topCheckBox.setObjectName("topCheckBox")
        self.outputFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.outputFilePath.setGeometry(QtCore.QRect(122, 220, 381, 20))
        self.outputFilePath.setObjectName("outputFilePath")
        self.subFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.subFilePath.setGeometry(QtCore.QRect(60, 10, 311, 20))
        self.subFilePath.setObjectName("subFilePath")
        self.magFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.magFilePath.setGeometry(QtCore.QRect(190, 50, 311, 20))
        self.magFilePath.setObjectName("magFilePath")
        self.topFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.topFilePath.setGeometry(QtCore.QRect(190, 110, 311, 20))
        self.topFilePath.setObjectName("topFilePath")
        self.gpsCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.gpsCheckBox.setGeometry(QtCore.QRect(70, 80, 121, 21))
        self.gpsCheckBox.setObjectName("gpsCheckBox")
        self.gpsFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.gpsFilePath.setGeometry(QtCore.QRect(190, 80, 311, 20))
        self.gpsFilePath.setObjectName("gpsFilePath")
        self.gpsBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.gpsBrowseButton.setGeometry(QtCore.QRect(510, 80, 71, 21))
        self.gpsBrowseButton.setObjectName("gpsBrowseButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Log Parser"))
        self.magBrowseButton.setText(_translate("MainWindow", "Browse..."))
        self.label_2.setText(_translate("MainWindow", "Sub Log"))
        self.subBrowseButton.setText(_translate("MainWindow", "Browse..."))
        self.label_3.setText(_translate("MainWindow", "Optional:"))
        self.topBrowseButton.setText(_translate("MainWindow", "Browse..."))
        self.runParseButton.setText(_translate("MainWindow", "Parse Logs"))
        self.label_4.setText(_translate("MainWindow", "Package as:"))
        self.saveAsMAT.setText(_translate("MainWindow", ".mat (struct)"))
        self.saveAsCSV.setText(_translate("MainWindow", ".csv"))
        self.saveAsXLSX.setText(_translate("MainWindow", ".xlsx"))
        self.outputBrowseButton.setText(_translate("MainWindow", "Browse..."))
        self.label_5.setText(_translate("MainWindow", "Log Output Directory"))
        self.magCheckBox.setText(_translate("MainWindow", "Magnetometer Log"))
        self.topCheckBox.setText(_translate("MainWindow", "Topside Log (Binary)"))
        self.gpsCheckBox.setText(_translate("MainWindow", "DGPS Log"))
        self.gpsBrowseButton.setText(_translate("MainWindow", "Browse..."))

